export const WORDS: string[] = [
  // nouns - objects
  'apple', 'anchor', 'arrow', 'atlas', 'axle',
  'badge', 'barrel', 'basket', 'beam', 'bell', 'blade', 'blanket', 'block', 'bolt', 'bottle',
  'branch', 'brick', 'bridge', 'brush', 'bucket', 'bulb', 'bundle',
  'cabin', 'cable', 'candle', 'canvas', 'carpet', 'castle', 'cellar', 'chain', 'channel',
  'chart', 'chest', 'chimney', 'chip', 'circle', 'clamp', 'clasp', 'clock', 'cloth',
  'cobalt', 'coil', 'collar', 'column', 'copper', 'corner', 'cotton', 'cover', 'crater',
  'crown', 'crystal', 'cube', 'cupboard', 'curtain',
  'dagger', 'desk', 'dial', 'dome', 'door', 'drawer', 'drum',
  'eagle', 'edge', 'ember',
  'fabric', 'fence', 'fiber', 'fiddle', 'filter', 'flag', 'flask', 'floor', 'flute', 'foam',
  'fossil', 'fountain', 'frame', 'funnel',
  'gate', 'gauge', 'gear', 'glass', 'globe', 'glove', 'grain', 'gravel', 'grid', 'grove',
  'guitar', 'hammer', 'handle', 'hatch', 'helmet', 'hinge', 'hook', 'horn',
  'iron', 'island',
  'jacket', 'jar', 'joint',
  'kettle', 'knob',
  'ladder', 'lamp', 'lance', 'latch', 'layer', 'ledge', 'lens', 'lever', 'lock',
  'marble', 'mask', 'mast', 'medal', 'mesh', 'mirror', 'module',
  'napkin', 'needle', 'notch',
  'orbit',
  'paddle', 'panel', 'patch', 'pencil', 'pillar', 'pillow', 'pipe', 'pivot', 'plank', 'plate',
  'plug', 'plume', 'pocket', 'post', 'prism', 'pulley',
  'quartz',
  'rail', 'ramp', 'ribbon', 'ridge', 'ring', 'rivet', 'rod', 'rope', 'rudder',
  'saddle', 'scale', 'seal', 'shelf', 'shield', 'signal', 'silver', 'slate', 'socket',
  'spiral', 'spoke', 'spring', 'stack', 'stake', 'stand', 'staple', 'stem', 'step',
  'stone', 'strap', 'string',
  'tablet', 'tank', 'thread', 'timber', 'token', 'torch', 'tower', 'track', 'tray',
  'trunk', 'tube', 'tunnel',
  'umbrella',
  'valve', 'vault', 'vessel',
  'wallet', 'wedge', 'wheel', 'window', 'wire',
  'zipper',

  // nouns - nature / places
  'beach', 'brook', 'canyon', 'cave', 'cliff', 'cloud', 'coast', 'coral',
  'creek', 'crest', 'crown', 'delta', 'desert', 'dune', 'dust',
  'field', 'fjord', 'flame', 'flood', 'floor', 'forest', 'frost',
  'geyser', 'glacier', 'glade', 'gorge', 'gulf',
  'harbor', 'heath', 'hill', 'hollow',
  'jungle',
  'lagoon', 'lake', 'lava', 'leaf',
  'marsh', 'meadow', 'mist', 'moss', 'mountain',
  'ocean', 'otter',
  'peak', 'pebble', 'plain', 'pond', 'pool',
  'rain', 'reef', 'ridge', 'river', 'rock',
  'sand', 'shore', 'slope', 'snow', 'soil', 'stream', 'summit', 'swamp',
  'tide', 'timber', 'tundra',
  'valley', 'vapor', 'vine', 'volcano',
  'wave', 'wetland', 'wind',

  // nouns - abstract / concepts
  'balance', 'barrier', 'beacon', 'border', 'boundary',
  'calm', 'chance', 'chaos', 'choice', 'clarity', 'concept', 'contrast', 'cycle',
  'data', 'dawn', 'depth', 'detail', 'direction', 'domain', 'draft',
  'echo', 'effort', 'element', 'energy', 'era', 'error', 'essence',
  'factor', 'failure', 'feature', 'focus', 'form', 'frame',
  'gap', 'goal', 'grace', 'growth',
  'habit', 'horizon',
  'impact', 'index', 'input',
  'kernel',
  'layer', 'limit', 'link', 'logic',
  'margin', 'measure', 'memory', 'method', 'model', 'moment', 'motion',
  'network', 'noise', 'notion',
  'object', 'option', 'order', 'output',
  'pattern', 'phase', 'pilot', 'point', 'power', 'process', 'progress', 'proof',
  'query',
  'radius', 'range', 'ratio', 'realm', 'reason', 'record', 'result', 'rhythm', 'route',
  'sample', 'scope', 'sector', 'series', 'source', 'space', 'speed', 'stage', 'state',
  'status', 'structure', 'system',
  'target', 'tension', 'theme', 'theory', 'threshold', 'time', 'topic', 'trace', 'trend',
  'unit', 'value', 'vector', 'version', 'vision', 'volume',
  'weight', 'width',
  'yield', 'zone',

  // verbs
  'adjust', 'align', 'apply', 'assert',
  'borrow', 'bounce', 'build',
  'cancel', 'capture', 'carry', 'catch', 'change', 'check', 'choose', 'claim', 'clean',
  'climb', 'close', 'collect', 'combine', 'compile', 'connect', 'convert', 'copy', 'create',
  'define', 'deliver', 'deploy', 'design', 'detect', 'develop', 'divide', 'draw', 'drive',
  'enable', 'enter', 'escape', 'expand', 'export', 'extend',
  'fetch', 'filter', 'finish', 'follow', 'format',
  'gather', 'generate', 'grant',
  'handle', 'hold',
  'import', 'inject', 'install', 'invent', 'invoke',
  'launch', 'listen', 'load',
  'manage', 'map', 'match', 'measure', 'merge', 'mount', 'move',
  'notice',
  'obtain', 'open', 'output',
  'parse', 'pause', 'perform', 'place', 'prepare', 'press', 'print', 'process', 'produce',
  'protect', 'prove', 'publish', 'push',
  'reach', 'read', 'rebuild', 'record', 'reduce', 'release', 'remove', 'render', 'repair',
  'replace', 'report', 'reset', 'resize', 'resolve', 'restart', 'return', 'reveal', 'review',
  'rotate', 'run',
  'save', 'scan', 'search', 'select', 'send', 'set', 'share', 'shift', 'show', 'solve',
  'sort', 'split', 'start', 'store', 'submit', 'sync',
  'test', 'toggle', 'track', 'transfer', 'trigger',
  'undo', 'update', 'upload',
  'validate', 'verify', 'view',
  'watch', 'wrap', 'write',

  // adjectives
  'active', 'actual', 'acute', 'agile', 'amber', 'ancient',
  'basic', 'bold', 'brief', 'bright', 'broad', 'broken', 'bronze',
  'calm', 'careful', 'central', 'certain', 'clean', 'clear', 'clever', 'closed', 'coastal',
  'cold', 'common', 'compact', 'complex', 'correct', 'crisp', 'curved', 'custom',
  'daily', 'dark', 'deep', 'dense', 'direct', 'distant', 'double', 'dry', 'durable',
  'early', 'easy', 'empty', 'equal', 'exact',
  'fair', 'fast', 'final', 'fixed', 'flat', 'fluid', 'formal', 'forward', 'fresh', 'front',
  'gentle', 'giant', 'global', 'golden', 'grand', 'gray', 'great', 'green',
  'hard', 'high', 'hollow', 'honest', 'humble',
  'ideal', 'inner', 'intact',
  'large', 'late', 'level', 'light', 'linear', 'local', 'logical', 'long', 'loose', 'lower',
  'minor', 'mobile', 'modern',
  'narrow', 'native', 'neutral', 'noble', 'normal',
  'open', 'outer',
  'partial', 'plain', 'polar', 'prime', 'proper', 'proud', 'pure',
  'quick', 'quiet',
  'rapid', 'raw', 'ready', 'real', 'rich', 'rigid', 'rough', 'round',
  'safe', 'sharp', 'short', 'silent', 'simple', 'slim', 'slow', 'small', 'smart', 'smooth',
  'soft', 'solid', 'stable', 'static', 'steady', 'steep', 'still', 'strong', 'subtle', 'swift',
  'tight', 'total', 'tough', 'true',
  'unique', 'upper',
  'valid', 'vast', 'vital', 'vivid',
  'warm', 'wide',
  'young',
];
